apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-minikube-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/surabhy/flask-k8s-gitops.git
    targetRevision: HEAD
    path: k8s/flask-app-v19
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
